services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=zoodb
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin:/pgadmin

volumes:
  pgadmin: