name: Build and Push Knowledge Image

on:
  push:
    paths:
      - "knowledge-search/**"
      - ".github/workflows/build-knowledge.yml"
    branches:
      - main
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-knowledge:
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      context: ./knowledge-search
      dockerfile: ./knowledge-search/Dockerfile
      image_name: ${{ github.repository }}/knowledge
