name: Build and Publish Docker to GHCR

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
        default: ghcr.io
      context:
        required: true
        type: string
      file:
        required: true
        type: string
      image-name:
        required: true
        type: string
    outputs:
      image-name-with-digest:
        description: "The full image name with digest"
        value: ${{ jobs.build.outputs.image-name-with-digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      image-name-with-digest: ${{ steps.set-output.outputs.image-name-with-digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: "v2.2.4"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref == 'refs/heads/main' }},suffix={{date 'YYYYMMDD'}}-{{sha}}
            type=sha,enable=${{ github.ref != 'refs/heads/main' }},prefix=sha-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }} # Optionally tag 'latest' for main

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image name with digest
        id: set-output
        run: |
          FULL_IMAGE_NAME="${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}@${{ steps.build-and-push.outputs.digest }}"
          echo "Image name with digest: $FULL_IMAGE_NAME"
          echo "image-name-with-digest=$FULL_IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
