name: Build and Deploy API

on:
  push:
    paths:
      - "assistant/**"
      - ".github/workflows/deploy-api.yml"
    branches:
      - main
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-api-image:
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      context: ./assistant
      dockerfile: ./assistant/Dockerfile
      image_name: ${{ github.repository }}/api
