name: Deploy Internal API to GHCR

on:
  #   push:
  #     branches: ["main"]
  workflow_dispatch:

jobs:
  build-docker-image:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-and-publish-docker-ghcr.yml
    with:
      image-name: ${{ vars.GHCR_ASSISTANT_API_IMAGE_NAME }}
      context: ./api
      file: Dockerfile

  deploy-to-azure-container-apps:
    needs: build-docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    strategy:
      matrix:
        environment:
          - staging
          - production
    environment: ${{ matrix.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ vars.CA_ASSISTANT_API_NAME }}
          resourceGroup: ${{ vars.CA_RESOURCE_GROUP }}
          imageToDeploy: ghcr.io/${{ needs.build.outputs.image-name-with-digest }}
