name: Deploy Internal API to GHCR

on:
  #   push:
  #     branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-and-publish-docker-ghcr.yml
    with:
      image-name: ${{ vars.GHCR_ASSISTANT_API_IMAGE_NAME }}
      context: ./api
      file: Dockerfile

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Call reusable deploy workflow for Assistant to Staging
        uses: ./.github/workflows/deploy-azure-container-app.yml
        with:
          image-name: ${{ needs.build_assistant.outputs.image-name-with-digest }}
          container-app-name: ${{ vars.CA_ASSISTANT_API_NAME }}
          resource-group: ${{ vars.CA_RESOURCE_GROUP }}
          target_environment: "staging"
