name: Deploy Internal API to GHCR

on:
  #   push:
  #     branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-and-publish-docker-ghcr.yml
    with:
      image-name: ${{ vars.CA_ASSISTANT_API_IMAGE_NAME }}
      context: ./api
      file: Dockerfile

  deploy:
    needs: build
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: ./.github/workflows/deploy-azure-container-app.yml
    with:
      image-name: ${{ needs.build.outputs.image-name-with-digest }}
      container-app-name: ${{ vars.CA_ASSISTANT_API_NAME }}
      resource-group: ${{ vars.CA_RESOURCE_GROUP }}
    secrets:
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
