name: Deploy Internal API to GHCR

on:
  #   push:
  #     branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-publish-docker-ghcr.yml
    with:
      registry: ghcr.io
      image-name: simenkristoffers1/internal-api
      file: ./internal-api/Dockerfile
